module.exports = {
  required: "필수 값입니다.",
  pwdFormat:
    "비밀번호는 8자 이상 16자 이하이어야 하고 숫자와 문자 1개 이상 반드시 포함 되어야 합니다.",
  titleFormat: "제목은 최대 20자입니다.",
  contentFormat: "내용은 최대 200자입니다.",
  notExistingProduct: "이미 삭제된 상품 입니다.",
  notEqualPwd: "비밀번호가 일치하지 않습니다.",
  existEmail: "이미 가입된 이메일입니다.",
  pleaseRetry: "다시 시도해주세요.",
  notExistingUser: "존재하지 않는 유저 입니다.",
  emailFormat: "올바른 이메일 형식이 아닙니다.",
  nameFormat: "이름은 최대 50자입니다.",
  emailLength: "이메일은 최대 100자입니다.",
  wrongFormat: "형식을 맞춰주세요.",
  notValidToken: "토큰의 유효 기간이 지났습니다.",
  existProduct: "이미 등록된 상품입니다.",
  notExistingOrder: "이미 취소된 주문입니다.",
  notValidDeleteRequest: "결제 후에는 주문 취소 시 관리자에게 문의 해주세요",
  notValidUpdateRequest: "결제 후에는 주문 수정 시 관리자에게 문의 해주세요",
  orderStatus: "결제 상태는 관리자만 수정할 수 있습니다.",
};
